doctrine:
    dbal:
        dbname: '%db_name%'
        host: '%db_host%'
        port: '%db_port%'
        user: '%db_user%'
        password: '%db_password%'
        driver: pdo_mysql

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Developer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Developer/Entity'
                prefix: 'App\Model\Developer\Entity'
                alias: Developer
            Position:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Position/Entity'
                prefix: 'App\Model\Position\Entity'
                alias: Position
            Project:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Project/Entity'
                prefix: 'App\Model\Project\Entity'
            Customer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Customer/Entity'
                prefix: 'App\Model\Customer\Entity'
                alias: Customer
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
